import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../constants/Colors'; 

const GlobalStyles = StyleSheet.create({
  safeAreaStyles: {
    flex: 1,
    backgroundColor: Colors.White,
  },
  mainContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.White,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.White,
  },
  buttonContainer: {
    width: "100%",
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  inputContainer: {
    flex: 1,
    height: 'auto',
    width: '80%',
    marginTop: 10,
  },
  containerInput: {
    marginTop: 32,
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: Colors.ModalOverlay,
  },
  modalContainer: {
    backgroundColor: Colors.White,
    width: '100%',
    padding: 24,
    paddingBottom: 40,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    alignItems: 'center',
    elevation: 5,
    shadowColor: Colors.ShadowBlack,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 10,
    paddingTop: Platform.OS === 'ios' ? 10 : 40.5,
    backgroundColor: Colors.White,
    borderBottomWidth: 1,
    borderBottomColor: Colors.LightBorder,
  },
  headerProductDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 15 : 38,
    paddingBottom: Platform.OS === 'ios' ? 7 : 7,
    borderBottomWidth: 1,
    borderBottomColor: Colors.LightBorder,
  },
  backButton: {
    paddingVertical: 5,
  },
  favoriteHeaderButton: {
    backgroundColor: Colors.WhiteTransparent90,
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.ShadowBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  
  productCard: {
    flex: 1,
    backgroundColor: Colors.White,
    borderRadius: 12,
    marginHorizontal: 5,
    marginVertical: 10,
    shadowColor: Colors.ShadowBlack,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 12,
    overflow: 'hidden',
  },
  imageContainer: {
    position: 'relative',
  },
  productImage: {
    width: '100%',
    height: 120,
    resizeMode: 'cover',
    backgroundColor: Colors.LightBackground,
  },
  favoriteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: Colors.WhiteTransparent95,
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.ShadowBlack,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 8,
  },
  productInfo: {
    padding: 12,
  },
  productPricing: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  productMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 50,
  },
  emptyStateIconContainer: {
    marginBottom: 16,
    alignItems: 'center',
  },
  
  errorState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 50,
  },
  
  loadingFooter: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  
  productsList: {
    padding: 15,
    paddingBottom: 100,
  },
  row: {
    justifyContent: 'space-between',
    marginHorizontal: 5,
  },
  
  buttonSpacer: {
    height: 15,
  },
  retryButton: {
    backgroundColor: Colors.Orange,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 6,
    shadowColor: Colors.ShadowBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
  },
  browseButton: {
    backgroundColor: Colors.Orange,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    shadowColor: Colors.ShadowBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
  },
  
  headerText: {
    fontSize: 30,
    fontWeight: '600',
    color: Colors.Black,
    lineHeight: 36,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.HeaderText,
    marginBottom: 2,
  },
  headerTitleProduct: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.HeaderText,
    textAlign: 'center',
    marginHorizontal: 10,
  },
  headerSubtitle: {
    fontSize: 14,
    color: Colors.HeaderSubtext,
    fontWeight: '500',
  },
  subHeaderText: {
    fontWeight: '500',
    fontSize: 16,
    color: Colors.Black,
    lineHeight: 28,
  },
  buttonText: {
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 26,
  },
  backText: {
    fontSize: 16,
    color: Colors.Orange,
    fontWeight: '600',
  },
  retryText: {
    color: Colors.White,
    fontWeight: '600',
  },
  browseButtonText: {
    color: Colors.White,
    fontWeight: '600',
    fontSize: 16,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.TextPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateText: {
    fontSize: 16,
    color: Colors.TextSecondary,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  errorText: {
    fontSize: 16,
    color: Colors.ErrorRed,
    textAlign: 'center',
    marginBottom: 20,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.TextPrimary,
    marginBottom: 4,
    lineHeight: 18,
  },
  productBrand: {
    fontSize: 12,
    color: Colors.Orange,
    fontWeight: '500',
    marginBottom: 6,
  },
  productDescription: {
    fontSize: 12,
    color: Colors.TextSecondary,
    lineHeight: 16,
    marginBottom: 8,
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.TextPrimary,
    marginRight: 8,
  },
  productDiscount: {
    fontSize: 12,
    color: Colors.SuccessGreen,
    fontWeight: '500',
  },
  productRating: {
    fontSize: 12,
    color: Colors.TextSecondary,
  },
  productStock: {
    fontSize: 12,
    color: Colors.TextSecondary,
  },
  createAccount: {
    fontWeight: '700',
    fontSize: 14,
    color: Colors.Orange,
    lineHeight: 19.6,
    marginLeft: 10,
  },
  noAccount: {
    fontWeight: '500',
    fontSize: 14,
    color: Colors.Black,
    lineHeight: 19.6,
    opacity: 0.6,
  },
  forgotText: {
    color: Colors.Orange,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 19.6,
  },
  rememberText: {
    color: Colors.Black,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 19.6,
    marginTop: 10,
    marginBottom: 10,
  },
  inputText: {
    fontWeight: '700',
    fontSize: 30,
  },
  inputHandlerText: {
    color: Colors.ErrorText,
    fontSize: 12,
    fontWeight: '400',
    margin: 10,
    textAlign: 'center',
  },
  plainText: {
    fontWeight: '400',
    fontSize: 16,
  },
  mediumText: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '500',
    color: Colors.DarkGrey,
  },
  bigText: {
    fontSize: 34,
    fontWeight: '800',
    color: Colors.Black,
    lineHeight: 41.5,
  },
  loadingText: {
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 15,
    marginBottom: 10,
    color: Colors.Orange,
  },
  
  logo: {
    height: 24,
    width: 132,
    marginBottom: 30,
  },
  img: {
    height: 18,
    width: 18,
  },
  
  containerInputBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 10,
  },
  inputBox: {
    width: '15%',
    height: 54,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.Grey,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rememberForgotContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  registrationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 70,
    marginBottom: 10,
  },
  breakLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  line: {
    width: "32%",
    height: 1,
    backgroundColor: Colors.Black,
  },
  orLogin: {
    fontWeight: '500',
    fontSize: 12,
    color: Colors.TextMuted,
    lineHeight: 16.8,
    opacity: 0.6,
  },
  
  scrollContainer: {
    flex: 1,
  },
  productDetailsImageContainer: {
    backgroundColor: Colors.LightBackground,
  },
  mainImage: {
    width: '100%',
    height: 300,
    backgroundColor: Colors.LightBackground,
  },
  thumbnailContainer: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  thumbnailContent: {
    alignItems: 'center',
  },
  thumbnailWrapper: {
    marginRight: 10,
    borderWidth: 2,
    borderColor: 'transparent',
    borderRadius: 8,
    overflow: 'hidden',
  },
  selectedThumbnail: {
    borderColor: Colors.Orange,
  },
  thumbnail: {
    width: 60,
    height: 60,
    borderRadius: 6,
  },
  productDetailsInfo: {
    padding: 20,
  },
  productDetailsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.TextPrimary,
    marginBottom: 5,
    lineHeight: 30,
  },
  productDetailsBrand: {
    fontSize: 16,
    color: Colors.Orange,
    fontWeight: '600',
    marginBottom: 15,
  },
  pricingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  productDetailsPrice: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.TextPrimary,
    marginRight: 15,
  },
  productDetailsDiscount: {
    fontSize: 16,
    color: Colors.SuccessGreen,
    fontWeight: '600',
    backgroundColor: Colors.DiscountBackground,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  metaContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: Colors.LightBorder,
  },
  productDetailsRating: {
    fontSize: 16,
    color: Colors.TextSecondary,
    fontWeight: '500',
  },
  productDetailsStock: {
    fontSize: 16,
    color: Colors.TextSecondary,
    fontWeight: '500',
  },
  descriptionSection: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.TextPrimary,
    marginBottom: 10,
  },
  description: {
    fontSize: 16,
    color: Colors.TextSecondary,
    lineHeight: 24,
  },
  detailsSection: {
    marginBottom: 25,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.LightBorder,
  },
  detailLabel: {
    fontSize: 16,
    color: Colors.TextSecondary,
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 16,
    color: Colors.TextPrimary,
    fontWeight: '400',
    textAlign: 'right',
    flex: 1,
    marginLeft: 20,
  },
  reviewsSection: {
    marginBottom: 100,
  },
  reviewCard: {
    backgroundColor: Colors.LightBackground,
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  reviewerName: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.TextPrimary,
  },
  reviewRating: {
    fontSize: 14,
  },
  reviewComment: {
    fontSize: 14,
    color: Colors.TextSecondary,
    lineHeight: 20,
    marginBottom: 5,
  },
  reviewDate: {
    fontSize: 12,
    color: Colors.TextMuted,
  },
  bottomActions: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: Platform.OS === 'ios' ? 15 : 20,
    borderTopWidth: 1,
    borderTopColor: Colors.LightBorder,
    backgroundColor: Colors.White,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addToCartButton: {
    backgroundColor: Colors.LightBackground,
    borderWidth: 1,
    borderColor: Colors.Orange,
    marginRight: 10,
  },
  buyNowButton: {
    backgroundColor: Colors.Orange,
    marginLeft: 10,
  },
  addToCartText: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.Orange,
  },
  buyNowText: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.White,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingDetailsText: {
    marginTop: 10,
    fontSize: 16,
    color: Colors.TextSecondary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  errorDetailsText: {
    fontSize: 18,
    color: Colors.ErrorRed,
    textAlign: 'center',
    marginBottom: 20,
  },
  favoriteContainer: {
    paddingHorizontal: 20,
    paddingBottom: 15,
    backgroundColor: Colors.White,
    borderTopWidth: 1,
    borderTopColor: Colors.LightBorder,
  },
  favoriteActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.LightBackground,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.BorderLight,
  },
  favoriteActionIconContainer: {
    marginRight: 8,
  },
  favoriteActionText: {
    fontSize: 14,
    fontWeight: '500',
  },
  
  timerContainer: {
    shadowColor: Colors.ShadowBlack,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 15,
  },
  timerContent: {
    backgroundColor: Colors.White,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: Colors.Orange,
    minWidth: 130,
    alignItems: 'center',
    shadowColor: Colors.Orange,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 8,
  },
  timerIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.Orange,
    marginBottom: 4,
    shadowColor: Colors.Orange,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 5,
  },
  timerTimeText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.TextPrimary,
    textAlign: 'center',
    lineHeight: 17,
    letterSpacing: 0.3,
  },
  timerUpdateText: {
    fontSize: 9,
    color: Colors.TextMuted,
    marginTop: 3,
    textAlign: 'center',
    fontWeight: '500',
  },
});

export default GlobalStyles;